### ISSUE TITLE
求操作说明

### ISSUE THREAD

**Issue by fatfish516** [zhangolve/search-engine-filter#8]
### 在设置里添加了要过滤的网站，为什么谷歌搜索结果中还包含？

<br />

![游候插件设置](https://i.loli.net/2018/12/15/5c1453d101e6e.png)

<br/>

#### 搜索结果如下:
<br/>

![搜索结果显示](https://i.loli.net/2018/12/15/5c145424b804a.png)

<br/>

#### 麻烦大佬指教下(实在是受不了CSDN 这一系列的网站了~)

**Comment by zhangolve** [comment]
你用的应该是chrome扩展吧，目前有个问题，添加完规则要再刷新一下页面，可能会在下个版本修改。
另外由于百度的变化，目前也不支持百度了。你可以看下其他的issue了解下问题

最后，不是大佬。这个扩展，是我学前端半年左右写的，后来有其他人参与完善。

**Comment by fatfish516** [comment]
不是，这是游候插件啊

**Comment by fatfish516** [comment]
![TIM截图20181215095803.png](https://i.loli.net/2018/12/15/5c145fc1a8446.png)

### 你看  我是在游候插件里设置的

**Comment by zhangolve** [comment]
油猴新版本没有更新，麻烦通过这个仓库首页chrome商店下载使用或者直接下载仓库根目录crx文件。

**Comment by fatfish516** [comment]
哦哦 也就是说 油候现在用不了是吧？Chrome扩展用了一下，但是呢只能用Google，百度的话结果不屏蔽。。

**Comment by fatfish516** [comment]
感谢作者分享的插件

**Comment by zhangolve** [comment]
是，我刚才说了。
也支持必应的。
后期会尝试把百度加上，但是有个坑，我在另外一个issue上提到过。

如果没有问题了，请关掉issue吧。

欢迎反馈。
